-------------- DIA UTIL E FIM DE SEMANA
CREATE PROCEDURE RETORNADIAUTILFIMSEMANA(@NOMEDIA VARCHAR(20), @FS CHAR(3) OUTPUT, @DIAU CHAR(3) OUTPUT)
AS
IF (@NOMEDIA = 'sábado' or @NOMEDIA = 'domingo')
BEGIN
	SET @FS = 'SIM' 
	SET @DIAU = 'NAO'
END

-------------- SEMESTRE E NOME SEMESTRE
CREATE PROCEDURE RETORNASEMESTRE(@M INT, @A INT, @S SMALLINT OUTPUT, @NS VARCHAR(20) OUTPUT)
AS
IF (@M > 6)
BEGIN
	SET @S = 2
	SET @NS = '2° Semestre / ' + CAST(@A AS VARCHAR(8))
END
ELSE
BEGIN
	SET @S = 1
	SET @NS = '1° Semestre / ' + CAST(@A AS VARCHAR(8))
END

-------------- FERIADOS
CREATE PROCEDURE RETORNAFERIADO(@M SMALLINT, @D SMALLINT, @F CHAR(3) OUTPUT)
AS
IF (@M = 1 AND @D = 1  OR @M =  3 AND @D = 30 OR
	@M = 4 AND @D = 21 OR @M =  5 AND @D =  1 OR 
	@M = 9 AND @D = 7  OR @M = 10 AND @D = 12 OR
	@M = 11 AND @D = 2 OR @M = 11 AND @D = 15 OR @M = 12 AND @D = 25)
BEGIN
	SET @F = 'SIM'
END
ELSE
BEGIN
	SET @F = 'NAO'
END

-------------- PREECHENDO A AUXILIAR DE TEMPO
CREATE PROCEDURE SP_AUX_TEMPO(@DATA_CARGA DATE, @DATEINICIAL DATE, @DATEFINAL DATE)
AS
SET LANGUAGE 'PORTUGUES' 
DECLARE 
	@DATE DATE, @DIA SMALLINT, @MES SMALLINT, @ANO INT, @NOMEMES VARCHAR(20),
	@SEMESTRE SMALLINT,	@FIMMES CHAR(3), @NOMEDIA VARCHAR(20), @FERIADO CHAR(3), @R INT,
	@NOMESEMESTRE VARCHAR(20), @ID INT, @FIMSEMANA CHAR(3), @DIAUTIL CHAR(3), 
	@DATEFIMMES DATE, @NIVEL VARCHAR(15)

SET @DATE = @DATEINICIAL
WHILE(@DATEFINAL >= @DATE)
	BEGIN
		SET @R = (SELECT IDAUX_TEMPO FROM STG.AUX_TEMPO WHERE DATA = CAST(@DATE AS DATE))					
		IF (@R IS NOT NULL)
			BEGIN
				PRINT 'Data já inserida no banco'
				BREAK
			END
		ELSE
			BEGIN
				SET @DIA = DATEPART(DD, @DATE)
				SET @NOMEDIA = DATENAME(DW, @DATE) 
				SET @MES = DATEPART(MM, @DATE)
				SET @ANO = DATEPART(YY, @DATE)
				SET @DATEFIMMES = EOMONTH(@DATE)
				SET @NOMEMES = DATENAME(MM, @DATE)
				SET @FERIADO = 'NAO'
				SET @FIMMES = 'NAO'
				SET @FIMSEMANA = 'NAO' 
				SET @DIAUTIL = 'SIM'
				SET @NIVEL = 'DIA'

				EXEC RETORNAFERIADO @MES, @DIA, @FERIADO OUTPUT
				EXEC RETORNADIAUTILFIMSEMANA @NOMEDIA, @FIMSEMANA OUTPUT, @DIAUTIL OUTPUT	

				IF (@FERIADO = 'SIM') SET @DIAUTIL = 'NAO'
				IF (@DATE = @DATEFIMMES) SET @FIMMES = 'SIM'

				EXEC RETORNASEMESTRE @MES, @ANO, @SEMESTRE OUTPUT, @NOMESEMESTRE OUTPUT

				INSERT INTO STG.AUX_TEMPO VALUES (@DATA_CARGA, @NIVEL, @DATE, @DIA, @NOMEDIA, @DIAUTIL, @FERIADO, @FIMSEMANA, @MES, @NOMEMES, @SEMESTRE, @NOMESEMESTRE, @ANO)
		
				IF (@FIMMES = 'SIM')
					BEGIN
						SET @NIVEL = 'MES'
						IF (NOT EXISTS(SELECT * FROM STG.AUX_TEMPO WHERE NIVEL = @NIVEL AND MES = @MES))
						BEGIN
							INSERT INTO STG.AUX_TEMPO VALUES (@DATA_CARGA, @NIVEL, NULL, NULL, NULL, NULL, NULL, NULL, @MES, @NOMEMES, @SEMESTRE, @NOMESEMESTRE, @ANO)
						END
						IF (@MES = 12 OR @MES = DATEPART(MM, @DATEFINAL))
							BEGIN
								SET @NIVEL = 'ANO'
								IF (NOT EXISTS(SELECT * FROM STG.AUX_TEMPO WHERE NIVEL = @NIVEL AND ANO = @ANO))
								BEGIN
									INSERT INTO STG.AUX_TEMPO VALUES (@DATA_CARGA, @NIVEL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @ANO)
								END
							END
					END
			END
		SET @DATE = DATEADD(DD, 1, @DATE)
	END


EXEC SP_AUX_TEMPO '20181017', '2018-01-01', '2018-10-30'
SELECT * FROM STG.AUX_TEMPO
TRUNCATE TABLE STG.AUX_TEMPO
