-------------- PREECHENDO A AUXILIAR DE TEMPO
ALTER PROCEDURE SP_DIM_TEMPO(@DATA_CARGA DATE)
AS
INSERT INTO DW.DIM_TEMPO 
SELECT NIVEL, DATA, DIA, DIA_SEMANA, DIA_UTIL, FERIADO, FIM_SEMANA, MES, NOME_MES, SEMESTRE, NOME_SEMESTRE, ANO 
FROM STG.AUX_TEMPO WHERE DATA_CARGA = @DATA_CARGA


EXEC SP_DIM_TEMPO '20181017' 
SELECT * FROM DW.DIM_TEMPO
SELECT * FROM STG.AUX_TEMPO 


-------------- STATUS
CREATE PROCEDURE SP_DIM_STATUS (@DATA DATE)
AS
DECLARE @ID INT, @N VARCHAR(50)
DECLARE C_STATUS CURSOR FOR 
SELECT IDAUX_STATUS, NOME FROM STG.AUX_STATUS 
WHERE DATA_CARGA = @DATA

OPEN C_STATUS 
FETCH C_STATUS INTO @ID, @N
WHILE (@@FETCH_STATUS = 0)
BEGIN
	DELETE FROM DW.DIM_STATUS WHERE ID_STATUS = @ID
	INSERT INTO DW.DIM_STATUS VALUES (@ID, @N)
	FETCH C_STATUS INTO @ID, @N
END 
CLOSE C_STATUS
DEALLOCATE C_STATUS

EXEC SP_DIM_STATUS '20181017'
SELECT * FROM STG.AUX_STATUS
SELECT * FROM DW.DIM_STATUS


-------------- MEDICO
CREATE PROCEDURE SP_DIM_MEDICO (@DATA DATE)
AS
DECLARE @ID INT, @NOME VARCHAR(50), @CRM VARCHAR(30), @ESPECIALIDADE VARCHAR(50)
DECLARE C_MEDICO CURSOR FOR
SELECT ID_MEDICO, NOME, CRM, ESPECIALIDADE FROM STG.AUX_MEDICO
WHERE DATA_CARGA = @DATA

OPEN C_MEDICO
FETCH C_MEDICO INTO @ID, @NOME, @CRM, @ESPECIALIDADE
WHILE (@@FETCH_STATUS = 0)
BEGIN
	DELETE FROM DW.DIM_MEDICO WHERE ID_MEDICO = @ID
	INSERT INTO DW.DIM_MEDICO VALUES (@ID, @NOME, @CRM, @ESPECIALIDADE)
	FETCH C_MEDICO INTO @ID, @NOME, @CRM, @ESPECIALIDADE
END
CLOSE C_MEDICO
DEALLOCATE C_MEDICO

EXEC SP_DIM_MEDICO '20181017'
SELECT * FROM STG.AUX_MEDICO
SELECT * FROM DW.DIM_MEDICO


-------------- CLINICA
CREATE PROCEDURE SP_DIM_CLINICA (@DATA DATE)
AS
DECLARE @ID INT, @RAZAO_SOCIAL VARCHAR(50), @CNPJ VARCHAR(30)
DECLARE C_CLINICA CURSOR FOR
SELECT ID_CLINICA, RAZAO_SOCIAL, CNPJ FROM STG.AUX_CLINICA
WHERE DATA_CARGA = @DATA

OPEN C_CLINICA
FETCH C_CLINICA INTO @ID, @RAZAO_SOCIAL, @CNPJ
WHILE (@@FETCH_STATUS = 0)
BEGIN
	DELETE FROM DW.DIM_CLINICA WHERE ID_CLINICA = @ID
	INSERT INTO DW.DIM_CLINICA VALUES (@ID, @RAZAO_SOCIAL, @CNPJ)
	FETCH C_CLINICA INTO @ID, @RAZAO_SOCIAL, @CNPJ
END
CLOSE C_CLINICA
DEALLOCATE C_CLINICA

EXEC SP_DIM_CLINICA '20181017'
SELECT * FROM STG.AUX_CLINICA
SELECT * FROM DW.DIM_CLINICA


-------------- PROCEDIMENTO ALTERADO
CREATE PROCEDURE SP_ALT_PROCEDIMENTO 
AS
UPDATE OLTP.TB_PROCEDIMENTO SET ATUALIZADO = 'N' 

-------------- PROCEDIMENTO
CREATE PROCEDURE SP_DIM_PROCEDIMENTO (@DATA DATE)
AS
DECLARE @ID INT, @NOME VARCHAR(50), @VALOR NUMERIC(10,2), @ATUALIZADO CHAR(1)
DECLARE C_PROCEDIMENTO CURSOR FOR
SELECT ID_PROCEDIMENTO, NOME, VALOR, ATUALIZADO FROM STG.AUX_PROCEDIMENTO
WHERE DATA_CARGA = @DATA

OPEN C_PROCEDIMENTO 
FETCH C_PROCEDIMENTO INTO @ID, @NOME, @VALOR, @ATUALIZADO
WHILE (@@FETCH_STATUS = 0)
BEGIN
	IF (NOT EXISTS(SELECT * FROM DW.DIM_PROCEDIMENTO WHERE ID_PROCEDIMENTO = @ID))
		BEGIN
			INSERT INTO DW.DIM_PROCEDIMENTO VALUES (@ID, @NOME, @VALOR, GETDATE(), NULL, 'SIM')
		END
	ELSE
		IF (@ATUALIZADO = 'N') 
			BEGIN
				UPDATE DW.DIM_PROCEDIMENTO SET NOME = @NOME WHERE ID_PROCEDIMENTO = @ID
			END
		ELSE
			BEGIN
				UPDATE DW.DIM_PROCEDIMENTO SET NOME = @NOME, DT_FIM = GETDATE(), FL_CORRENTE = 'NAO' WHERE ID_PROCEDIMENTO = @ID
				INSERT INTO DW.DIM_PROCEDIMENTO VALUES (@ID, @NOME, @VALOR, GETDATE(), NULL, 'SIM')
			END
	FETCH C_PROCEDIMENTO INTO @ID, @NOME, @VALOR, @ATUALIZADO
END
CLOSE C_PROCEDIMENTO
DEALLOCATE C_PROCEDIMENTO
EXEC SP_ALT_PROCEDIMENTO 

EXEC SP_DIM_PROCEDIMENTO '20181017'
SELECT * FROM DW.DIM_PROCEDIMENTO
SELECT * FROM STG.AUX_PROCEDIMENTO


-------------- PROCEDIMENTO AGENDADO ALTERADO
CREATE PROCEDURE SP_ALT_PROC_AGENDADO 
AS
UPDATE OLTP.TB_PROC_AGENDADO SET ATUALIZADO = 'N' 


-------------- PROCEDIMENTO AGENDADO
ALTER PROCEDURE SP_FATO_AGENDAMENTO (@DATA DATE)
AS
DECLARE @ID INT, @TEMPO INT, @PROC INT, @CLINICA INT, @MEDICO INT, @STATUS INT, @QUANTIDADE INT, @ATUALIZADO CHAR(1),
@DW_PROC INT, @DW_CLINICA INT, @DW_MEDICO INT, @DW_STATUS INT

DECLARE C_AGENDAMENTO CURSOR FOR
SELECT ID_PROC_AGENDADO, IDAUX_TEMPO, ID_PROCEDIMENTO, ID_CLINICA,
ID_MEDICO, IDAUX_STATUS, QUANTIDADE, ATUALIZADO 
FROM STG.FATO_AGENDAMENTO WHERE DATA_CARGA = @DATA

OPEN C_AGENDAMENTO
FETCH C_AGENDAMENTO INTO @ID, @TEMPO, @PROC, @CLINICA, @MEDICO, @STATUS, @QUANTIDADE, @ATUALIZADO 

WHILE (@@FETCH_STATUS = 0)
BEGIN
	SELECT @DW_PROC = IDDIM_PROCEDIMENTO FROM DW.DIM_PROCEDIMENTO WHERE ID_PROCEDIMENTO = @PROC 
	SELECT @DW_CLINICA = IDDIM_CLINICA FROM DW.DIM_CLINICA WHERE ID_CLINICA = @CLINICA
	SELECT @DW_MEDICO = IDDIM_MEDICO FROM DW.DIM_MEDICO WHERE ID_MEDICO = @MEDICO
	SELECT @DW_STATUS = IDDIM_STATUS FROM DW.DIM_STATUS WHERE ID_STATUS = @STATUS

	IF (NOT EXISTS(SELECT * FROM DW.FATO_AGENDAMENTO WHERE ID_PROC_AGENDADO = @ID))
		BEGIN
			INSERT INTO DW.FATO_AGENDAMENTO VALUES (@ID, @TEMPO, @DW_PROC, @DW_CLINICA, @DW_MEDICO, @DW_STATUS, @QUANTIDADE, GETDATE(), NULL, 'SIM')
		END
	ELSE
		IF (@ATUALIZADO = 'N') 
			BEGIN
				UPDATE DW.FATO_AGENDAMENTO SET 
					DIM_TEMPO_IDDIM_TEMPO = @TEMPO, 
					DIM_PROCEDIMENTO_IDDIM_PROCEDIMENTO = @DW_PROC, 
					DIM_CLINICA_IDDIM_CLINICA = @DW_CLINICA,
					DIM_MEDICO_IDDIM_MEDICO = @DW_MEDICO
				WHERE ID_PROC_AGENDADO = @ID
			END
		ELSE
			BEGIN
				UPDATE DW.FATO_AGENDAMENTO SET 
					DIM_TEMPO_IDDIM_TEMPO = @TEMPO, 
					DIM_PROCEDIMENTO_IDDIM_PROCEDIMENTO = @DW_PROC, 
					DIM_CLINICA_IDDIM_CLINICA = @DW_CLINICA,
					DIM_MEDICO_IDDIM_MEDICO = @DW_MEDICO,
					DT_FIM = GETDATE(), 
					FL_CORRENTE = 'NAO'
				WHERE ID_PROC_AGENDADO = @ID
				INSERT INTO DW.FATO_AGENDAMENTO VALUES (@ID, @TEMPO, @DW_PROC, @DW_CLINICA, @DW_MEDICO, @DW_STATUS, @QUANTIDADE, GETDATE(), NULL, 'SIM')
			END
	FETCH C_AGENDAMENTO INTO @ID, @TEMPO, @PROC, @CLINICA, @MEDICO, @STATUS, @QUANTIDADE, @ATUALIZADO 
END
CLOSE C_AGENDAMENTO
DEALLOCATE C_AGENDAMENTO
EXEC SP_ALT_PROCEDIMENTO 

EXEC SP_FATO_AGENDAMENTO '20181017'
SELECT * FROM DW.FATO_AGENDAMENTO
SELECT * FROM STG.FATO_AGENDAMENTO


